[package]
name = "tcl"
version = "0.1.0"
authors = ["trash-iine <kantera.primenumbers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
